services:
  - type: web
    name: github-graphs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py  # ← Change this if your file is named differently
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: graphs-storage
      mountPath: /opt/render/project/src/static/graphs
      sizeGB: 1  # $1/month for persistent graph storage