services:
  - type: web
    name: github-graphs
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    workDir: PersonalWebsite
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: graphs-storage
      mountPath: /opt/render/project/src/PersonalWebsite/static/graphs
      sizeGB: 1